const HOME_ROUTE = "/home",
    LOGIN_ROUTE = "/login",
    CARDS_ROUTE = "/cards",
    APPS_ROUTE = "/applications",
    DASH_ROUTE = "/home",
    PROFILE_ROUTE = "/profile",
    TUITION_ROUTE = "/tuition",
    REGISTER_ROUTE = "/account",
    PAYMENTS_ROUTE = "/consults/payments",
    STEPONE_ROUTE = "/step-one",
    CHOOSE_SCHOOL_OPTION_ROUTE = "/choose-option",
    SEARCH_SCHOOL_ROUTE = "/search",
    VIEW_SCHOOL_ROUTE = "/view-school",
    VIEW_COURSE_ROUTE = "/view-course",
    COURSES_ROUTE = "/courses",
    SEARCH_ROUTE = "/search",
    EXPLORE_ROUTE = "/explore",
    WELCOME_ROUTE = "/welcome",
    CONSULTS_ROUTE = "/consults",
    CONSULTS_CREDORES_ROUTE = "/consults/credores",
    CONSULTS_CREDIT_SUCCESS_ROUTE = "/consults/success",
    CONSULTS_INFO_CREDOR_ROUTE = "/consults/info-credor",
    CONSULTS_CONFIRM_CREDIT_ROUTE = "/consults/confirm-credit",
    DETAILS_PAGE_ROUTE = "/detailsI",
    PAY_SCHOOL_ROUTE = "/payments/pay-school",
    PAY_TRANSPORT_ROUTE = "/pay-transport",
    PAY_COURSES_ROUTE = "/pay-courses",
    SERVICES_VACANCIES_ROUTE = "/services/vacancies",
    SERVICES_VACANCY_SUCCESS_ROUTE = "/services/vacancy-success",
    SERVICES_VACANCY_RESULTS_ROUTE = "/services/vacancy-results",
    SERVICES_VIEW_VACANCIES_ROUTE = "/services/view-vacancy",
    PAY_FOOD_ROUTE = "/pay-food",
    TRANSFERS_ROUTE = "/transferencias/transfer",
    PAY_FIT_ROUTE = "/pay-fit",
    CONFIRMATION_ROUTE = "/payments/confirmation",
    CARD_INFO_ROUTE = "/consults/infoMulti",
    SERVICES_ROUTE = "/services",
    CONFIRM_CONFIRMATION_ROUTE = "/payments/institution/confirm-confirmation",
    VIEW_SCHOLARSHIPS_ROUTE = "/services/view-scholarships",
    SERVICES_VACANCY_APPLICATION_ROUTE = "/services/vacancy-application",
    EDUCATIONAL_MOVEMENTS_ROUTE = "/educacional/movements",
    SCHOLARSHIPS_ROUTE = "/services/scholarships",
    CONSULT_CREDITS_ROUTE = "/consults/credits",
    CONSULT_MOVMENTS_ROUTE = "/consultas/movimentos",
    ENROLLEMENTS_ROUTE = "/matricula"


export const routes = {
    CARD_INFO_ROUTE,
    SCHOLARSHIPS_ROUTE,
    SERVICES_VACANCY_RESULTS_ROUTE,
    CONSULTS_CREDIT_SUCCESS_ROUTE,
    SERVICES_VIEW_VACANCIES_ROUTE,
    PAY_SCHOOL_ROUTE,
    CONFIRM_CONFIRMATION_ROUTE,
    CONFIRMATION_ROUTE,
    SERVICES_VACANCIES_ROUTE,
    SERVICES_VACANCY_APPLICATION_ROUTE,
    CONSULTS_INFO_CREDOR_ROUTE,
    SERVICES_VACANCY_SUCCESS_ROUTE,
    SERVICES_ROUTE,
    CONSULTS_CONFIRM_CREDIT_ROUTE,
    TRANSFERS_ROUTE,
    PAY_FOOD_ROUTE,
    PAY_TRANSPORT_ROUTE,
    PAY_COURSES_ROUTE,
    COURSES_ROUTE,
    PAY_FIT_ROUTE,
    CONSULT_CREDITS_ROUTE,
    CONSULT_MOVMENTS_ROUTE,
    WELCOME_ROUTE,
    CONSULTS_ROUTE,
    EDUCATIONAL_MOVEMENTS_ROUTE,
    SEARCH_ROUTE,
    ENROLLEMENTS_ROUTE,
    HOME_ROUTE,
    TUITION_ROUTE,
    PAYMENTS_ROUTE,
    VIEW_SCHOLARSHIPS_ROUTE,
    VIEW_SCHOOL_ROUTE,
    CHOOSE_SCHOOL_OPTION_ROUTE,
    SEARCH_SCHOOL_ROUTE,
    VIEW_COURSE_ROUTE,
    EXPLORE_ROUTE,
    STEPONE_ROUTE,
    REGISTER_ROUTE,
    LOGIN_ROUTE,
    DETAILS_PAGE_ROUTE,
    CONSULTS_CREDORES_ROUTE,
    DASH_ROUTE,
    PROFILE_ROUTE,
    CARDS_ROUTE,
    APPS_ROUTE

} as const 